levels = ['grunnkrets_id', 'delomrade', 'kommune', 'fylke']
levels_ext = ['grunnkrets_id', 'delomrade', 'kommune', 'fylke', 'country']
next_nevel = {'grunnkrets_id':'delomrade', 'delomrade':'kommune', 'kommune':'fylke'}
next_nevel_ext = {'grunnkrets_id':'delomrade', 'delomrade':'kommune', 'kommune':'fylke', 'fylke':'country'}
income_cols = ['all_households', 'singles', 'couple_without_children',	'couple_with_children', 'other_households',	'single_parent_with_children']
plaace_cols = ['plaace_cat_1',	'plaace_cat_2',	'plaace_cat_3',	'plaace_cat_4']
plaace_cols_alt = ['lv1',	'lv2',	'lv3',	'lv4']
plaace_cols_explain = ['lv1_desc',	'lv2_desc','lv3_desc','lv4_desc']
plaace_cols_ext = ['plaace_cat_0','plaace_cat_1',	'plaace_cat_2',	'plaace_cat_3',	'plaace_cat_4']
next_plaace_col = { 'plaace_cat_2':'plaace_cat_1','plaace_cat_3':'plaace_cat_2','plaace_cat_4':'plaace_cat_3'}
next_plaace_col_ext = { 'plaace_cat_1':'plaace_cat_0','plaace_cat_2':'plaace_cat_1','plaace_cat_3':'plaace_cat_2','plaace_cat_4':'plaace_cat_3'}